### PR TITLE
54 BaseX admin module function signatures

### PR DESCRIPTION
**Pull request by CanOfBees**
This PR adds a set of function signatures for the BaseX 9.0 Admin module.

### CODE REVIEW

**Comment by rhdunn** [comment]
Review feedback:

1.  The `%a:since` annotation should match the version the API was introduced. For BaseX, see the Change Log at the bottom. The `admin` module was introduced in `7.5`, so most functions should be labelled as such. New signatures should be marked correctly, for example the `$merge` argument variant of `admin:logs` was added in version 7.8.2.

2.  The deleted functions (e.g. `admin:users`) should be annotated with `%a:until` annotations like `%a:until("basex", "8.0", "user:list-details#2")` -- here, the replacement uses the NamedFunctionRef syntax ("qname#arity"). You can use the wiki history to get the signatures of the deleted functions.

3.  Type changes I don't currently have a good markup in XQuery for. I have been making them comments, e.g. for the archive:options return type, you can use `(: as [7.3]element() [8.5]map(*) :)` as is done in the MarkLogic code and it can be replaced once the plugin has support for that versioned type syntax.

NOTE: Updates that don't affect the signatures don't need to be included (but may when documentation is included).

**Comment by CanOfBees** [comment]
Thanks so much for the feedback - this is super helpful.
> Review feedback:
> 
>     1. The `%a:since` annotation should match the version the API was introduced. For BaseX, see the Change Log at the bottom. The `admin` module was introduced in `7.5`, so most functions should be labelled as such. New signatures should be marked correctly, for example the `$merge` argument variant of `admin:logs` was added in version 7.8.2.
> 
Great - this answers a question I had but didn't ask: how you wanted to approach the major/minor/patch versioning. 

>     2. The deleted functions (e.g. `admin:users`) should be annotated with `%a:until` annotations like `%a:until("basex", "8.0", "user:list-details#2")` -- here, the replacement uses the NamedFunctionRef syntax ("qname#arity"). You can use the wiki history to get the signatures of the deleted functions.
> 
Perfect - thanks for pointing that out.

>     3. Type changes I don't currently have a good markup in XQuery for. I have been making them comments, e.g. for the archive:options return type, you can use `(: as [7.3]element() [8.5]map(*) :)` as is done in the MarkLogic code and it can be replaced once the plugin has support for that versioned type syntax.
> 
> 
> NOTE: Updates that don't affect the signatures don't need to be included (but may when documentation is included).

I'll make changes as soon as I'm able. Thanks again for taking your time with this!

**Comment by rhdunn** [comment]
Thanks for the update. For the removed functions, also include the `a:since` annotations (and any others that are relevant). preferrably in the order `since`, `deprecated`, `until`, `variadic`.

**Comment by CanOfBees** [comment]
Another question, sorry: I have a function that was superseded by two different functions; e.g.
`archive:write` was replaced by `archive:create-from` and `archive:extract-to`. How would this be annotated? My understanding is that an annotation can't be reused/repeated in a declaration, so:
```xquery
declare %a:since("basex", "7.7") %a:deprecated("basex", "8.0", "archive:create-from#2") function archive:write ... external;
declare %a:since("basex", "7.7") %a:deprecated("basex", "8.0", "archive:create-from#3") function archive:write ... external;
```
Is the `a:see-also` annotation intended for situations like this?

Thanks!

**Comment by rhdunn** [comment]
XQuery does not mention forbidding duplicate annotations (https://www.w3.org/TR/xquery-31/#id-annotations). It is just that for many annotations (`%private`, etc.) it does not make sense.

The `$replacement` parameter of `a:deprecated` and `a:until` is for direct replacements. The intention (not yet working) is that the plugin can use this in the deprecated/removed message and provide an action to do the rename.

I'm currently using `a:see-also` for MarkLogic `xdmp:from-json => xdmp:from-json-string`.

I think deprecated/until could still work -- e.g. `%a:until("basex", "8.3", "archive:create-from#3", "archive:extract-to#3")`. This way, if there are multiple replacements the plugin can infer this is not a direct replacement and just offer a message instead of a "replace with ..." action (or maybe offering a "replace with ..." action for each replacement).

NOTE: `a:deprecated` is for when the function is still available in that version, but is not intended for use and may be removed in a future version. As such, `a:until` is correct for `archive:write` as 8.3 removes that function.

**Comment by CanOfBees** [comment]
You're right - I had misunderstood a statement of "Multiple annotations (with different names) can also be specified" to mean that annotations had to be unique. Sorry for the confusion and I appreciate the examples and explanation!

**Comment by rhdunn** [comment]
Merged, thanks.

**Pull request merged**
